name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.13.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.13.x
    - run: yarn install
    - run: |
        docker pull junderw/bitcoinjs-regtest-server
        docker run -d -p 127.0.0.1:8080:8080 junderw/bitcoinjs-regtest-server
    - run: yarn test
    - name: Coverage
      uses: codecov/codecov-action@v1
      if: github.ref == 'refs/heads/master'
